version: "2"

services:
  mongo:
    image: mongo:3.4
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - network-reactive

  spring-boot-reactive:
    build:
      context: ../spring-boot-reactive-web
    image: spring-boot-reactive-web-tpd
    environment:
      # Overrides the host in the Spring Boot application to use the Docker's hostname
      - SPRING_DATA_MONGODB_HOST=mongo
    ports:
      - "8080:8080"
    networks:
      - network-reactive

  angular-reactive:
    build:
      context: ../angular-reactive
    image: angular-reactive-tpd
    ports:
      - "4200:1827"
    networks:
      - network-reactive

volumes:
  mongodata:

networks:
  network-reactive:
